name: Availability Check - Google Cloud API Service
description: "Check if the specified Google Cloud API service is enabled and enable it if not."
inputs:
  gcp_project_id:
    description: "The Google Cloud project ID."
    required: true
  api_service:
    description: "The Google Cloud API service to check and enable (e.g., compute.googleapis.com, storage.googleapis.com)."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if specified API service is enabled
      id: check_api_service
      run: |
        # Ensure the API service is provided
        if [ -z "${{ inputs.api_service }}" ]; then
          echo "Error: API_SERVICE is not set.";
          exit 1;
        fi
        
        # Check if the specified API service is enabled
        ENABLED=$(gcloud services list --enabled --filter="${{ inputs.api_service }}" --format="value(NAME)")
        
        if [ "$ENABLED" == "${{ inputs.api_service }}" ]; then
          echo "${{ inputs.api_service }} is already enabled."
          echo "::set-output name=enable_api_service::false"
        else
          echo "${{ inputs.api_service }} is not enabled."
          echo "::set-output name=enable_api_service::true"
        fi

    - name: Enable the specified API service
      if: steps.check_api_service.outputs.enable_api_service == 'true'
      run: |
        echo "Enabling ${{ inputs.api_service }} API..."
        gcloud services enable ${{ inputs.api_service }} --project=${{ inputs.gcp_project_id }}
        echo "${{ inputs.api_service }} API enabled."

    - name: Verify specified API service is enabled
      run: |
        gcloud services list --enabled --filter="${{ inputs.api_service }}" --format="value(NAME)"
        echo "Verified ${{ inputs.api_service }} is enabled."
