name: Requested-API Activation 

on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: 'The Google Cloud project ID'
        required: true
      api_service:
        description: 'The Google Cloud API service to enable (e.g., compute.googleapis.com)'
        required: true
      authenticate_at_path:
        description: "With gcp-key at path which you'd like to use for authentication."
        required: true
      path_list:
        description: "List of paths you'd like to write the gcp-key."
        required: true
jobs:
  enable-api-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ inputs.gcp_project_id }}

      - name: Google Cloud Authentication
        uses: buildeventdriven/resource_creation/.github/actions/google-auth@main
        with:
          gcp_project_id: ${{ inputs.gcp_project_id }}
          access_key: ${{ secrets.GCP_SA_KEY }}
          authenticate_at_path: ${{inputs.authenticate_at_path }}
          path_list: ${{inputs.path_list }}

      - name: Enable API Service
        uses: buildeventdriven/resource_creation/.github/actions/enable-api-service@main
        with:
          gcp_project_id: ${{ inputs.gcp_project_id }}
          api_service: ${{ inputs.api_service }}
