name: 'Terraform Setup Action'
description: 'Reusable Terraform setup action for dependency check, formating init, validate, and GCP authentication'
inputs:
  terra_directory:
    description: "Input directory that you want to setup terraform onto"
    required: true
runs:
  using: "composite"
  steps:
    # Install Dependencies
    - name: Install Pre-Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install Main Dependencies (Only If Missing)
      run: |
        while IFS= read -r package || [[ -n "" ]]; do
          # Ignore comments and empty lines in requirements.txt
          [[ "" =~ ^#.*$ || -z "" ]] && continue
          # Extract the actual package name (handle version constraints like "numpy==1.21.0")
          pkg_name=
          # Check if package is installed
          python -c "import " 2>/dev/null || pip install ""
        done < requirements.txt

    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Set up GCP credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ github.workspace }}/terraform-scripts/${{ inputs.terra_directory }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ github.workspace }}/terraform-scripts/${{ inputs.terra_directory }}
