name: Availability Check - Compute Engine API
description: "Check if the Compute Engine API is enabled and enable it if not."
inputs:
  gcp_project_id:
    description: "The Google Cloud project ID."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if Compute Engine API is enabled
      id: check_compute_api
      run: |
        ENABLED=$(gcloud services list --enabled --filter="compute.googleapis.com" --format="value(NAME)")
        if [ "$ENABLED" == "compute.googleapis.com" ]; then
          echo "Compute Engine API is already enabled."
          echo "::set-output name=enable_compute_api::false"
        else
          echo "Compute Engine API is not enabled."
          echo "::set-output name=enable_compute_api::true"
        fi

    - name: Enable Compute Engine API
      if: steps.check_compute_api.outputs.enable_compute_api == 'true'
      run: |
        gcloud services enable compute.googleapis.com --project=${{ inputs.gcp_project_id }}
        echo "Compute Engine API enabled."

    - name: Verify Compute Engine API is enabled
      run: |
        gcloud services list --enabled --filter="compute.googleapis.com" --format="value(NAME)"
        echo "Verified Compute Engine API is enabled."
