name: Google Cloud Authentication
description: "Authenticate with Google Cloud using a service account key."
inputs:
  gcp_project_id:
    description: "The Google Cloud project ID."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      shell: bash
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' | jq '.' > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project "$gcp_project_id"
        gcloud auth list
        rm /tmp/gcp-key.json

    # - name: Authenticate with Google Cloud
    #   shell: bash
    #   run: |
    #     chmod +x .github/scripts/google-auth.sh
    #     .github/scripts/google-auth.sh
    #   env:
    #     gcp_project_id: ${{ inputs.gcp_project_id }}
    #     authenticate_at_path: ${{ inputs.authenticate_at_path }}
