name: 'Enable Google Cloud API Service'
description: 'Enable a specified Google Cloud API service.'
inputs:
  gcp_project_id:
    description: 'The Google Cloud project ID'
    required: true
  api_service:
    description: 'The Google Cloud API service to enable (e.g., compute.googleapis.com)'
    required: true
  access_key:
    description: 'GCP Service Account Key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ inputs.access_key }}
        project_id: ${{ inputs.gcp_project_id }}

    - name: Google Cloud Authentication
      uses: ./github/actions/google-auth
      with:
        GCP_SA_KEY: ${{ inputs.access_key }}
        GCP_PROJECT: ${{ inputs.gcp_project_id }}

    - name: Enable API Service
      uses: ./github/actions/enable-api-service
      with:
        gcp_project_id: ${{ inputs.gcp_project_id }}
        api_service: ${{ inputs.api_service }}
