name: Google Cloud Authentication
description: "Authenticate with Google Cloud using a service account key."
inputs:
  access_key:
    description: "The Google Cloud service account key in JSON format."
    required: true
  gcp_project_id:
    description: "The Google Cloud project ID."
    required: true
  path_list:
    description: "Paths that you want to write GCP key at."
    required: true 
  authenticate_at_path:
    description: 'Path to gcp key, available for authentication.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Write key to desired path/s
      shell: bash
      run: |
        chmod +x .github/scripts/write-gcp-key.sh
        .github/scripts/write-gcp-key.sh
      env:
        access_key: ${{ inputs.access_key }}
        path_list: ${{ inputs.path_list }}

    - name: Authenticate with Google Cloud
      shell: bash
      run: |
        chmod +x .github/scripts/google-auth.sh
        .github/scripts/google-auth.sh
      env:
        gcp_project_id: ${{ inputs.gcp_project_id }}
        authenticate_at_path: ${{ inputs.authenticate_at_path }}
