name: Authenticating-GCP
description: "Authenticate with Google Cloud using a service account key."
inputs:
  gcp_project_id:
    description: "The Google Cloud project ID."
    required: true
  access_key:
    description: "The Google Cloud project ID."
    required: true
  authenticate_at_path:
    description: "With gcp-key at path which you'd like to use for authentication."
    required: true
  path_list:
    description: "List of paths you'd like to write the gcp-key."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Write key to desired path/s
      shell: bash
      run: |
        chmod +x .github/scripts/write-gcp-key.sh
        .github/scripts/write-gcp-key.sh
      env:
        access_key: ${{ inputs.access_key }}
        path_list: ${{ inputs.path_list }}

    - name: Authenticate with Google Cloud
      shell: bash
      run: |
        chmod +x .github/scripts/google-auth.sh
        .github/scripts/google-auth.sh
      env:
        gcp_project_id: ${{ inputs.gcp_project_id }}
        authenticate_at_path: ${{ inputs.authenticate_at_path }}
