name: Google Cloud Authentication
description: "Authenticate with Google Cloud using a service account key."
inputs:
  access_key:
    description: "The Google Cloud service account key in JSON format."
    required: true
  gcp_project_id:
    description: "The Google Cloud project ID."
    required: true
  # gcp_key_file_path:
  #   escription: 'Path to pre-written gcp key, available for use.'
  #   required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Text to JSON to JSON file
      shell: bash
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' | jq '.' > /tmp/gcp-key.json

    - name: Authenticate with Google Cloud
      shell: bash
      run: |
        gcloud auth activate-service-account --key-file = /tmp/gcp-key.json
        gcloud config set project ${{ inputs.gcp_project_id }}
        gcloud auth list
    
    # ${{ inputs.gcp_key_file_path }}

    - name: Clean up
      shell: bash
      run: |
        rm /tmp/gcp-key.json
