name: Activate Compute API Service

on:
  workflow_dispatch:
jobs:
  trigger-enable-api-service:
    runs-on: ubuntu-latest
    env:
      API_SERVICE_TO_ENABLE: "compute.googleapis.com"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Check Type of GCP Service Account Key
        run: |
          echo "Type of GCP_SA_KEY: $(echo '${{ secrets.GCP_SA_KEY }}' | file -)"

    # Make sure you use appropriate account key. And, not use one key in every project/use-case.  
      - name: Write GCP Service Account Key to a json file
        shell: bash
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | jq '.' > /tmp/gcp-key.json

      - name: Trigger Enable API Service Workflow
        run: |
          gh workflow run request-service-api.yml --ref main \
            --field gcp_project_id="${{ secrets.GCP_PROJECT }}" \
            --field api_service="${{ env.API_SERVICE_TO_ENABLE }}" \
            --field access_key="${{ secrets.GCP_SA_KEY }}"
        env:
            GH_TOKEN: ${{ secrets.TERRAFORM_PAT }}  

      # - name: API Service Request
      #   uses: buildeventdriven/resource_creation/.github/actions/request-api-service@main
      #   with:
      #     gcp_project_id: ${{ secrets.GCP_PROJECT }}
      #     api_service: ${{ env.API_SERVICE_TO_ENABLE }}
      #     access_key: ${{ secrets.GCP_SA_KEY }}
