name: Enabling-Compute API Service

on:
  workflow_dispatch:
jobs:
  trigger-enable-api-service:
    runs-on: ubuntu-latest
    env:
      # When you assign a list Make sure here are no spaces before or after comma , e.g. "/tmp/gcp-key.json,/terraform-scripts/gcp-key.json"
      # Also you don't need to assign square brackets at the start and end. 
      API_SERVICE_TO_ENABLE: "compute.googleapis.com"
      PATH_LIST: "/tmp/gcp-key.json"
      GCP_AUTHENTICATE_AT: "/tmp/gcp-key.json"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Enable API Service Workflow
        run: |
          gh workflow run buildeventdriven/resource_creation/.github/workflows/subflows/request-service-api.yml --ref main \
            --field gcp_project_id="${{ secrets.GCP_PROJECT }}" \
            --field api_service="${{ env.API_SERVICE_TO_ENABLE }}" \
            --field path_list="${{ env.PATH_LIST }}" \
            --field authenticate_at_path="${{ env.GCP_AUTHENTICATE_AT }}"
        env:
            GH_TOKEN: ${{ secrets.TERRAFORM_PAT }}  
