name: Activate Compute API Service

on:
  workflow_dispatch:
jobs:
  trigger-enable-api-service:
    runs-on: ubuntu-latest
    env:
      API_SERVICE_TO_ENABLE: "compute.googleapis.com"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: API Service Request
      #   uses: buildeventdriven/resource_creation/.github/actions/request-api-service@main
      #   with:
      #     gcp_project_id: ${{ secrets.GCP_PROJECT }}
      #     api_service: ${{ env.API_SERVICE_TO_ENABLE }}
      #     access_key: ${{ secrets.GCP_SA_KEY }}

      - name: Trigger Enable API Service Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'request-service-api.yml'
          ref: 'main'  # Specify the branch to run the workflow from
          inputs: 
            gcp_project_id: ${{ secrets.GCP_PROJECT }}
            api_service: ${{ env.API_SERVICE_TO_ENABLE }}
            access_key: ${{ secrets.GCP_SA_KEY }}