name: Activate Compute API Service

on:
  workflow_dispatch:
jobs:
  trigger-enable-api-service:
    runs-on: ubuntu-latest
    env:
      API_SERVICE_TO_ENABLE: "compute.googleapis.com"
    steps:
      - name: Trigger the Enable API Service Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: enable-api-service.yml  # The target workflow to trigger
          ref: refs/heads/main  # Specify the branch (e.g., main)
          inputs:
            gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}  # GCP Project ID
            api_service: ${{ env.API_SERVICE_TO_ENABLE }} # API service to be enabled
            access_key: ${{ secrets.GCP_SA_KEY }}  # Service account key from secrets
