name: Enabling-Compute API Service

on:
  workflow_dispatch:
jobs:
  trigger-enable-api-service:
    runs-on: ubuntu-latest
    env:
      API_SERVICE_TO_ENABLE: "compute.googleapis.com"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Enable API Service Workflow
        run: |
          gh workflow run request-service-api.yml --ref main \
            --field gcp_project_id="${{ secrets.GCP_PROJECT }}" \
            --field api_service="${{ env.API_SERVICE_TO_ENABLE }}"
        env:
            GH_TOKEN: ${{ secrets.TERRAFORM_PAT }}  

      # - name: API Service Request
      #   uses: buildeventdriven/resource_creation/.github/actions/request-api-service@main
      #   with:
      #     gcp_project_id: ${{ secrets.GCP_PROJECT }}
      #     api_service: ${{ env.API_SERVICE_TO_ENABLE }}
      #     access_key: ${{ secrets.GCP_SA_KEY }}
      # When you assign a list Make sure here are no spaces before or after comma , e.g. "/tmp/gcp-key.json,/terraform-scripts/gcp-key.json"
      # Also you don't need to assign square brackets at the start and end. 
