name: Instance Management CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-22.04 # Keeping it locked in to 22.04, avoiding any update issues when happens on GitHub's side. 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Verify Terraform Files Exist
        run: |
          if [ ! -f terraform-scripts/main.tf ]; then
            echo "Error: No Terraform configuration files found in terraform-scripts/"
            exit 1
          fi
       - name: Current Directory
        run: pwd

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform-scripts

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform-scripts

      - name: Check Terraform Formatting
        run: terraform fmt -check
        working-directory: terraform-scripts

      # Google authentication flow needs to run before running terraform-apply 
      - name: Run Google Cloud Authentication
        run: gh workflow run ci-google-auth.yml || true  # Ensures it doesn't fail the pipeline
      
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
        working-directory: terraform-scripts

      - name: Run ShellCheck
        run: |
          sudo apt-get install -y shellcheck
          shellcheck infra/*.sh scripts/*.sh

      - name: Run health check script
        run: ./scripts/health-check.sh

      - name: Install Pre-Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install Main Dependencies (Only If Missing)
        run: |
          while IFS= read -r package || [[ -n "" ]]; do
            # Ignore comments and empty lines in requirements.txt
            [[ "" =~ ^#.*$ || -z "" ]] && continue
            # Extract the actual package name (handle version constraints like "numpy==1.21.0")
            pkg_name=
            # Check if package is installed
            python -c "import " 2>/dev/null || pip install ""
          done < requirements.txt

      - name: Install Google Cloud CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli
          gcloud --version

      - name: Run Ruff Linter
        run: python -m ruff check .  # Runs ruff on all Python files.

      - name: Auto-Fix Formatting with Black (if running manually)
        if: github.event_name == 'pull_request'
        run: black .  # Auto-formats code (this won't block CI)

      - name: Run Tests
        run: pytest tests/ || true  # Allows test failures but pipeline continues
