name: Google Cloud Authentication - Runner's Authentication

on:
  push:
    paths:
      - ".github/workflows/ci-google-auth.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  setup-google-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        run: |
          # Save the secret to a file properly
          echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          
      - name: Verify JSON Format and Authenticate
        run: |
          cat gcp-key.json | jq empty || echo "JSON is invalid!"

          # Ensure the file is correctly formatted
          cat gcp-key.json

          # Authenticate with the Service Account
          gcloud auth activate-service-account --key-file=gcp-key.json

          # Set GCP Project
          gcloud config set project ${{ secrets.GCP_PROJECT }}

          # Verify authentication
          gcloud auth list

          # Ensure the key file is accessible
          ls -l gcp-key.json
