name: Google Cloud Authentication

on:
  push:
    paths:
      - ".github/workflows/ci-google-auth.yml"
  workflow_dispatch: 

jobs:
  setup-google-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Save GCP Service Account Key (Properly)
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | jq '.' > gcp-key.json

      - name: Save GCP Service Account Key - Also under terraform-scripts
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | jq '.' > ${{ github.workspace }}/terraform-scripts/gcp-key.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud auth list
