name: Google Cloud Authentication - Runner's Authentication

on:
  push:
    paths:
      - ".github/workflows/ci-google-auth.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  setup-google-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud secrets versions access latest --secret=GCP_SA_KEY --project=${{ secrets.GCP_PROJECT }} > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth list
