name: Google Cloud Authentication

on:
  push:
    paths:
      - ".github/workflows/ci-google-auth.yml"

jobs:
  setup-google-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set executable permission on the google-auth.sh script
        run: chmod +x ./scripts/google-auth.sh

      - name: Authenticate with Google Cloud using google-auth.sh
        run: |
          ./scripts/google-auth.sh
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}  # Your Google Cloud Service Account Key
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}  # Your Google Cloud Project ID

      - name: Verify Authentication
        run: |
          gcloud auth list
