name: Plan-Apply Kafka Brokers

on:
  workflow_dispatch:  # Manually triggered pipeline

jobs:
  trigger-ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger CI/CD Pipeline
      uses: peter-evans/workflow-dispatch@v1
      with:
        workflow: 'terra-env-pipeline.yml'  # Trigger the CI/CD pipeline
        ref: 'main'  # The branch to run the pipeline on
        inputs: {}  # You can pass inputs if necessary, or leave empty

  terraform:
    runs-on: ubuntu-latest
    needs: trigger-ci-cd-pipeline  # Ensure the CI/CD pipeline finishes first

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terraform Plan
      run: terraform plan -var-file=terraform.auto.tfvars
      working-directory: ${{ github.workspace }}/terraform-scripts

    # - name: Auto apply variables
    #   run: terraform apply -auto-approve -var-file=terraform.auto.tfvars
    #   working-directory: ${{ github.workspace }}/terraform-scripts
