name: Plan-Apply Kafka Brokers

on:
  workflow_dispatch:  # Manually triggered pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your Google Cloud Project ID

      - name: Authenticate to Google Cloud
        run: |
          chmod +x ./scripts/google-auth.sh
          ./scripts/google-auth.sh
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}  # Your Google Cloud Service Account Key
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}  # Your Google Cloud Project ID
          
      - name: Verify Authentication
        run: |
          gcloud auth list
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.auto.tfvars
        working-directory: ${{ github.workspace }}/terraform-scripts

      # - name: Auto apply variables
      #   run: terraform apply -auto-approve -var-file=terraform.auto.tfvars
      #   working-directory: ${{ github.workspace }}/terraform-scripts
