name: Google Cloud Authentication

on:
  workflow_call:  # This makes the workflow reusable and callable by other workflows

jobs:
  google-auth-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your Google Cloud Project ID

      - name: Save GCP Service Account Key (Properly)
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | jq '.' > /tmp/gcp-key.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth list

      - name: Clean up
        run: |
          rm /tmp/gcp-key.json
